id = "move-aptos"
name = "move-aptos"
version = "0.0.2"
schema_version = 1
authors = ["simons <reggiesimons2cy@gmail.com>"]
description = "Move on Aptos language support for Zed"
repository = "https://github.com/caoyang2002/zed-move-aptos"

[language_servers.move-language-server]
name = "move"
language = "Move"

[grammars.move]
repository = "https://github.com/caoyang2002/tree-sitter-move-aptos"
commit = "ce22921df73ef24ecc2d3d3f2d41547e5c74638f"
