id = "move"
name = "move"
version = "0.0.1"
schema_version = 1
authors = ["simons <reggiesimons2cy@gmail.com>"]
description = "Move on Aptos language support for Zed"
repository = "https://github.com/caoyang2002/zed-move-aptos"

[grammars.move]
repository = "https://github.com/caoyang2002/tree-sitter-move-aptos"
commit = "b7758b645c2b194974ddbf081ee9ef90a7d00e1a"
