id = "move"
name = "move"
description = "Move on Aptos language support for Zed"
version = "0.0.2"
schema_version = 1
authors = ["simons <reggiesimons2cy@gmail.com>"]
repository = "https://github.com/caoyang2002/zed-move-aptos"

[grammars.move]
repository = "https://github.com/caoyang2002/tree-sitter-move-aptos"
commit = "b7758b645c2b194974ddbf081ee9ef90a7d00e1a"

# repository = "https://github.com/tree-sitter/tree-sitter-rust.git"
# commit = "6b7d1fc73ded57f73b1619bcf4371618212208b1"
